name: Pre-release check

on:
  pull_request:
    branches:
      - master

jobs:
  prepare:

    runs-on: ubuntu-latest

    steps:
      - name: Check head ref
        if: startsWith(github.head_ref, 'release') == false
        run: |
          echo head ref is not a release branch.
          exit 1

      - name: Checkout
        uses: actions/checkout@v1