name: Pre-release check

on:
  pull_request:
    branches:
      - master

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    if: "startsWith(github.head_ref, 'release')"
    steps:
      - run: echo Prepare is passed.

  check:
    name: Check
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install bundler
          bundle install
          danger